/**
 * EverFern Desktop — Text to Tool Call Parser
 *
 * Catches cases where a model writes tool signatures purely in text (e.g. naked python-like string calls
 * or unformatted JSON blocks) instead of emitting formal tool-call objects.
 */

import type { AgentTool } from '../runner/types';
import type { ToolCall } from '../../lib/ai-client';
import { validateAndCorrectSkillPath, resolveSkillPath } from '../../lib/skills-sync';

// Tool name aliases for backward compatibility and model-specific variations
const TOOL_NAME_ALIASES: Record<string, string> = {
  'read_file': 'read',
  'write_file': 'write',
  'edit_file': 'edit',
  'find_files': 'find',
  'grep_files': 'grep',
  'list_files': 'ls',
  'view_file': 'read',
  'write_to_file': 'write',
  'replace': 'edit',
  'run_command': 'terminal_execute',
  'bash': 'terminal_execute',
  'executePwsh': 'terminal_execute',
};

function normalizeToolName(toolName: string): string {
  return TOOL_NAME_ALIASES[toolName.toLowerCase()] || toolName;
}

export function parseTextToToolCalls(
  textContent: string,
  definedTools: AgentTool[]
): { toolCalls: ToolCall[]; scrubbedContent: string; parseError?: string } {
  const toolCalls: ToolCall[] = [];
  let scrubbedContent = textContent;
  let parseErrorStr: string | undefined;

  console.log(`[TextToTool] 🔍 Starting parser with ${textContent.length} chars, ${definedTools.length} defined tools`);
  console.log(`[TextToTool] 📋 Defined tools: ${definedTools.map(t => t.name).join(', ')}`);

  // 1. Strip <think> and <thought> blocks before parsing so we don't accidentally parse JSON narrated inside reasoning
  scrubbedContent = scrubbedContent.replace(/<(?:think|thought)>[\s\S]*?<\/(?:think|thought)>/ig, '').trim();

  // 1b. Match formal <tool_call> blocks first
  const toolCallRegex = /<tool_call>([\s\S]*?)<\/tool_call>/gi;
  let tcMatch;
  while ((tcMatch = toolCallRegex.exec(scrubbedContent)) !== null) {
    const blockContent = tcMatch[1].trim();
    let parsedArgs: any = null;
    let toolName = '';

    try {
      // It might be pure JSON
      const parsed = JSON.parse(blockContent);
      toolName = parsed.name || parsed.tool || '';
      parsedArgs = parsed.arguments || parsed.args || parsed.parameters || { ...parsed };
      delete parsedArgs.name;
      delete parsedArgs.tool;
    } catch (e) {
      // Might be a weird YAML/JSON hybrid like:
      // {"name": "write", "arguments": {"path": "..."}}
      // Or just name: write \n arguments: {...}
      const nameMatch = blockContent.match(/"name"\s*:\s*"([^"]+)"/i) || blockContent.match(/name\s*:\s*"?([^"\n]+)"?/i);
      if (nameMatch) toolName = nameMatch[1];

      // Try to extract arguments object
      const argsMatch = blockContent.match(/"arguments"\s*:\s*(\{[\s\S]*?\})/i) || blockContent.match(/arguments\s*:\s*(\{[\s\S]*?\})/i);
      if (argsMatch) {
        try { parsedArgs = JSON.parse(argsMatch[1]); } catch (e2) {}
      }
    }

    const normalizedName = normalizeToolName(toolName);
    if (toolName && parsedArgs && definedTools.some(t => t.name === normalizedName)) {
      // Map common argument variations
      if (['terminal_execute', 'run_command', 'bash', 'executePwsh'].includes(normalizedName)) {
        if (parsedArgs.CommandLine && !parsedArgs.command) {
          parsedArgs.command = parsedArgs.CommandLine;
        }
        if (parsedArgs.cmd && !parsedArgs.command) {
          parsedArgs.command = parsedArgs.cmd;
        }
      }

      toolCalls.push({
        id: `tc-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
        name: normalizedName,
        arguments: parsedArgs
      });
      scrubbedContent = scrubbedContent.replace(tcMatch[0], '').trim();
      console.log(`[TextToTool] 🧩 Formalized <tool_call> tag for: ${toolName}`);
    }
  }

  // We no longer blindly strip markdown fences globally, as this ruins actual code snippets
  // generated by the LLM intended for the user's chat context. We will surgically remove fences manually.

  // 2. Match computer_use(task="...") or other common tool patterns
  // 2. Match computer_use(task="...") or other common tool patterns
  const cuMatch = scrubbedContent.match(/(?:computer[_ ]use)\s*\(\s*task\s*=\s*["']([^"']{0,1000})["']\s*\)/i);
  if (cuMatch) {
    console.log(`[TextToTool] 🧩 Formalized text-based tool call: computer_use`);
    toolCalls.push({
      id: `tc-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      name: 'computer_use',
      arguments: { task: cuMatch[1] }
    });
    scrubbedContent = scrubbedContent.replace(cuMatch[0], '').trim();
  }

  // 2b. Match prefixed calls with flexible naming: _call:computer_use, call:computer use, etc.
  const prefixRegex = /(?:_)?call:([a-z0-9_ ]+)\s*\{([\s\S]{0,2000}?)\}/gi;
  let pMatch;
  while ((pMatch = prefixRegex.exec(scrubbedContent)) !== null) {
      let rawToolName = pMatch[1].trim();
      // Normalize 'computer use' to 'computer_use'
      const normalizedMatchName = rawToolName.replace(/\s+/g, '_').toLowerCase();
      const toolName = normalizeToolName(normalizedMatchName);
      const argsRaw = pMatch[2].trim();
      
      if (definedTools.some(t => t.name === toolName)) {
          console.log(`[TextToTool] 🧩 Formalized prefixed tool call: ${toolName}`);
          
          let parsedArgs: any = null;
          try {
              // Try parsing as JSON first (may need to convert single quotes)
              const jsonReady = argsRaw.replace(/'/g, '"');
              parsedArgs = JSON.parse(`{\${jsonReady}}`);
          } catch (e) {
              // Fallback to key=value extraction
              parsedArgs = {};
              const kvRegex = /([a-z0-9_]+)\s*[:=]\s*(?:"([^"]*)"|'([^']*)'|([^,}\s]+))/gi;
              let kv;
              while ((kv = kvRegex.exec(argsRaw)) !== null) {
                  parsedArgs[kv[1]] = kv[2] ?? kv[3] ?? kv[4];
              }
          }
          
          if (parsedArgs && Object.keys(parsedArgs).length > 0) {
              toolCalls.push({
                  id: `tc-prefixed-\${Date.now()}-\${Math.random().toString(36).slice(2, 6)}`,
                  name: toolName,
                  arguments: parsedArgs
              });
              scrubbedContent = scrubbedContent.replace(pMatch[0], '').trim();
          }
      }
  }

  // 3. Match system_files(action="...", root="...", ...) patterns written in text
  const sfRegex = /system_files\s*\(\s*([\s\S]{0,2000}?)\)/gi;
  const sfMatches = Array.from(scrubbedContent.matchAll(sfRegex));
  if (sfMatches.length > 0) {
    for (const sfMatch of sfMatches) {
      const argsStr = sfMatch[1];
      const parsedArgs: Record<string, unknown> = {};
      const kvRegex = /(\w+)\s*=\s*(?:"([^"]{0,1000})"|'([^']{0,1000})'|(\S{1,100}))/g;
      let kvMatch;
      while ((kvMatch = kvRegex.exec(argsStr)) !== null) {
        const key = kvMatch[1];
        const val = kvMatch[2] ?? kvMatch[3] ?? kvMatch[4];
        if (key === 'recursive') {
          parsedArgs[key] = val === 'true' || val === 'True';
        } else if (key === 'maxEntries') {
          parsedArgs[key] = parseInt(val, 10);
        } else {
          parsedArgs[key] = val;
        }
      }
      if (parsedArgs.action) {
        console.log(`[TextToTool] 🧩 Formalized text-based tool call: system_files(action=${parsedArgs.action})`);
        toolCalls.push({
          id: `tc-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
          name: 'system_files',
          arguments: parsedArgs,
        });
      }
      scrubbedContent = scrubbedContent.replace(sfMatch[0], '').trim();
    }
  }

  // 4. Match formal function-style calls: name(arg1="val", arg2='val')
  // Use negative lookbehind to prevent matching method calls like f.write() or obj.read()
  // IMPORTANT: Skip tools that take multi-line content (write, edit) — the regex can't handle
  // Python scripts with parentheses inside the content arg.
  const SKIP_FUNCTION_STYLE = new Set(['write', 'edit', 'write_file', 'edit_file']);
  const functionRegex = /(?<!\.)\b([a-z0-9_]+)\s*\(([\s\S]{0,2000}?)\)/gi;
  let match;
  const discoveredCalls: any[] = [];

  while ((match = functionRegex.exec(scrubbedContent)) !== null) {
    const toolName = match[1];
    const argsRaw = match[2];

    // Skip tools that take multi-line content — regex can't handle them
    if (SKIP_FUNCTION_STYLE.has(toolName)) continue;

    if (definedTools.some(t => t.name === toolName)) {
      const args: Record<string, any> = {};
      const argRegex = /([a-z0-9_]+)\s*=\s*(?:"([^"]{0,1000})"|'([^']{0,1000})'|([^,\s\)]+))/gi;
      let argMatch;
      let foundNamed = false;
      while ((argMatch = argRegex.exec(argsRaw)) !== null) {
        const key = argMatch[1];
        const val = argMatch[2] || argMatch[3] || argMatch[4];
        args[key] = val;
        foundNamed = true;
      }

      // Positional argument fallback: tool_name("value")
      if (!foundNamed && argsRaw.trim().length > 0) {
        const quotedMatch = argsRaw.trim().match(/^(?:"([^"]{0,1000})"|'([^']{0,1000})')$/);
        if (quotedMatch) {
           const val = quotedMatch[1] || quotedMatch[2];
           const toolDef = definedTools.find(t => t.name === toolName);
           // Try to infer target property from AgentTool's schema
           if (toolDef && toolDef.parameters && typeof toolDef.parameters === 'object' && 'properties' in toolDef.parameters) {
             const props = (toolDef.parameters as any).properties;
             const firstProp = Object.keys(props)[0];
             if (firstProp) args[firstProp] = val;
           }
        }
      }

      // Validate: reject clearly broken extractions
      if (toolName === 'run_command' && args.CommandLine && args.CommandLine.length < 5) {
        console.log(`[TextToTool] \u26a0\ufe0f Rejecting truncated command for run_command: "${args.CommandLine}"`);
        continue;
      }

      discoveredCalls.push({
        id: `tc-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
        name: toolName,
        arguments: args,
        rawMatch: match[0]
      });
    }
  }

  // 4b. Explicit support for python-style write() tool calls
  // Models often cheat by outputting write(path="...", content="""...""")
  const writeCheatRegex = /write\s*\(\s*path\s*=\s*["']([^"']{0,256})["']\s*,\s*content\s*=\s*(?:"""|''')([\s\S]{0,100000}?)(?:"""|''')\s*\)/gi;
  let writeMatch;
  while ((writeMatch = writeCheatRegex.exec(scrubbedContent)) !== null) {
    if (definedTools.some(t => t.name === 'write' || t.name === 'write_file')) {
      const pId = `tc-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
      console.log(`[TextToTool] 🧩 Formalized explicit python-style write() tool call`);
      
      // Preserve the code inside the content parameter
      let content = writeMatch[2];
      
      // Remove escaping if the model tried to escape backslashes
      content = content.replace(/\\\\/g, '\\');
      
      discoveredCalls.push({
        id: pId,
        name: 'write',
        arguments: { path: writeMatch[1], content: content },
        rawMatch: writeMatch[0]
      });
    }
  }

  if (discoveredCalls.length > 0) {
    console.log(`[TextToTool] 🧩 Formalized ${discoveredCalls.length} function-style calls`);
    for (const c of discoveredCalls) {
      if (!toolCalls.find(tc => tc.name === c.name && JSON.stringify(tc.arguments) === JSON.stringify(c.arguments))) {
        toolCalls.push({ id: c.id, name: c.name, arguments: c.arguments });
      }
      scrubbedContent = scrubbedContent.replace(c.rawMatch, '');
    }
    scrubbedContent = scrubbedContent.trim();
  }

  // 5. Match generic action=name(...) pattern if applicable
  const genericMatch = scrubbedContent.match(/action=([a-z_]+)\((.*?)\)/i);
  if (genericMatch) {
    const actionName = genericMatch[1];
    console.log(`[TextToTool] 🧩 Formalized action pattern: ${actionName}`);
    if (actionName === 'computer_use' && !toolCalls.find(tc => tc.name === 'computer_use')) {
       const taskMatch = genericMatch[2].match(/task\s*=\s*"(.*?)"/);
       toolCalls.push({
         id: `tc-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
         name: 'computer_use',
         arguments: { task: taskMatch ? taskMatch[1] : 'Perform automation' }
       });
       scrubbedContent = scrubbedContent.replace(genericMatch[0], '').trim();
    }
  }

  // 6. Match generic JSON blocks that aren't wrapped in markdown backticks
  try {
    const jsonBlocks: { str: string; start: number; end: number }[] = [];
    let braceCount = 0;
    let currentBlockStart = -1;
    let inString = false;
    let isEscaped = false;

    // Fast and robust brace balancer to extract independent JSON blocks
    for (let i = 0; i < scrubbedContent.length; i++) {
        const char = scrubbedContent[i];

        if (inString) {
            if (char === '\\') isEscaped = !isEscaped;
            else if (char === '"' && !isEscaped) inString = false;
            else isEscaped = false;
        } else {
            if (char === '"') {
                inString = true;
            } else if (char === '{') {
                if (braceCount === 0) currentBlockStart = i;
                braceCount++;
            } else if (char === '}') {
                braceCount--;
                if (braceCount === 0 && currentBlockStart !== -1) {
                    jsonBlocks.push({ str: scrubbedContent.slice(currentBlockStart, i + 1), start: currentBlockStart, end: i });
                    currentBlockStart = -1;
                }
            }
        }
    }

    let newScrubbedContent = '';
    let lastCopiedIndex = 0;

    // Process blocks in forward order to cleanly build the final string
    for (let b = 0; b < jsonBlocks.length; b++) {
      const block = jsonBlocks[b];
      let jsonStr = block.str;

      console.log(`[TextToTool] 📋 Raw JSON block extracted: ${jsonStr.slice(0, 150)}`);

      // LLMs notoriously try to escape single quotes and backticks in JSON strings, which is invalid JSON.
      // But we must be careful not to destroy escaped double quotes.
      jsonStr = jsonStr.replace(/\\`/g, '`').replace(/\\'/g, "'");

      // Handle the "triple quote" issue: "key": """value"""
      // This often happens when LLMs try to put multi-line content or complex commands in JSON.
      // Instead of an aggressive regex, we surgically convert """ to " only at boundaries.
      if (jsonStr.includes(':"""')) {
        jsonStr = jsonStr.replace(/:\s*"""/g, ':"');
        jsonStr = jsonStr.replace(/"""(?=\s*[,}\]])/g, '"');
      }
      
      // Clean up standalone triple-quotes
      jsonStr = jsonStr.replace(/"""/g, '"');

      console.log(`[TextToTool] 🔧 After quote normalization: ${jsonStr.slice(0, 150)}`);
      // At this point, we only trust basic cleanup.
      // Do NOT run eager regex replacements that try to "add missing quotes" because they
      // inevitably destroy complex Python logic strings (e.g. slicing on '}' inside F-strings).

      // 2. Fix trailing commas before closing braces/brackets
      jsonStr = jsonStr.replace(/,\s*([}\]])/g, '$1');

      // ═══════════════════════════════════════════════════════════════
      // CRITICAL: Detect Python Code vs JSON
      // Python dicts use single quotes and contain function calls like len(), .nunique(), etc
      // ═══════════════════════════════════════════════════════════════
      const hasToolKey = /"tool"\s*:/.test(jsonStr) || /"name"\s*:/.test(jsonStr);
      const isPythonCode = !hasToolKey && /[']\w+[']\s*:|len\(|\.nunique\(|\.strftime\(|\.mode\(\)|pd\.|df\.|datetime\.now|os\.path|\.to_csv\(|\.str\.|\.groupby\(|\.pivot_table\(/.test(jsonStr);

      if (isPythonCode) {
        console.log(`[TextToTool] 🐍 Detected standalone Python code block (no tool key), skipping JSON parsing`);
        // This is Python code, not JSON - skip this block entirely
        continue;
      }

      console.log(`[TextToTool] 📝 Attempting JSON parse: ${jsonStr.slice(0, 100)}...`);
      console.log(`[TextToTool] 🔧 Fixed JSON: ${jsonStr}`);

      let parsed: any;
      try {
        parsed = JSON.parse(jsonStr);
      } catch (parseError) {
        console.log(`[TextToTool] ⚠️  JSON.parse failed: ${parseError instanceof Error ? parseError.message : String(parseError)}`);
        console.log(`[TextToTool] 🔧 Attempting custom malformed JSON extraction...`);

        // Helper function to unescape JSON strings
        function unescapeJsonString(str: string): string {
          // Must replace \\\\ first (escaped backslash) before other escapes
          return str
            .replace(/\\\\/g, '\x00')    // Temporarily replace \\ with null char
            .replace(/\\n/g, '\n')       // \n → newline
            .replace(/\\r/g, '\r')       // \r → carriage return
            .replace(/\\t/g, '\t')       // \t → tab
            .replace(/\\b/g, '\b')       // \b → backspace
            .replace(/\\f/g, '\f')       // \f → form feed
            .replace(/\\"/g, '"')        // \" → quote
            .replace(/\x00/g, '\\');     // Replace null char back with single backslash
        }

        // Fallback: Extract key-value pairs from severely malformed JSON
        // This regex handles colons inside quoted values (Windows paths) better.
        parsed = {};
        
        // 1. Try to find "key": "value" patterns
        // We look for "key" : followed by either a quoted string (handling escaped quotes)
        // or a non-comma/non-brace value.
        const kvPattern = /"?([a-zA-Z0-9_-]+)"?\s*:\s*(?:(["'])([\s\S]*?)(?<!\\)\2|([^,}\]]+))/g;
        
        let kvMatch;
        while ((kvMatch = kvPattern.exec(jsonStr)) !== null) {
          const key = kvMatch[1];
          let value = kvMatch[3] ?? kvMatch[4];
          
          if (value !== undefined) {
            value = value.trim();
            // Remove trailing commas, braces if they got swept up in unquoted match
            if (!kvMatch[2]) {
              value = value.replace(/[,}\]]+$/, '').trim();
            }
            
            parsed[key] = unescapeJsonString(value);
            console.log(`[TextToTool]   Extracted: "${key}" = "${parsed[key]?.slice(0, 100)}..."`);
          }
        }
        
        // 2. Special case for the "skill" key which models often malform (e.g. "skill "link")
        if (!parsed.skill) {
           const skillMatch = jsonStr.match(/"skill\s*"?\s*[:\s]?\s*"?([a-z0-9_-]+)"?/i);
           if (skillMatch) {
             parsed.skill = skillMatch[1];
             console.log(`[TextToTool]   Recovered skill from malformed text: ${parsed.skill}`);
           }
        }

        if (Object.keys(parsed).length === 0) {
          console.log(`[TextToTool] ❌ Custom extraction also failed, JSON is too malformed`);
          throw parseError;  // Re-throw original error
        }
        console.log(`[TextToTool] ✅ Custom extraction recovered ${Object.keys(parsed).length} key-value pairs`);
      }

      const toolData = parsed.toolbench || parsed;

      console.log(`[TextToTool] 🔍 Parsed JSON data:`, {
        hasTool: !!toolData.tool,
        hasName: !!toolData.name,
        hasSkill: !!toolData.skill,
        hasPath: !!toolData.path,
        hasArguments: !!toolData.arguments,
        allKeys: Object.keys(toolData)
      });

      // Normalize tool name (read_file -> read, write_file -> write, etc.)
      const rawToolName = toolData.tool || toolData.name;
      const normalizedToolName = rawToolName ? normalizeToolName(rawToolName) : null;

      console.log(`[TextToTool] 🔄 Tool name normalization: "${rawToolName}" -> "${normalizedToolName}"`);

      let identifiedCall = false;

      // Handle {"tool": "write", "path": "..."} format
      if (normalizedToolName && definedTools.some(t => t.name === normalizedToolName)) {
         const tName = normalizedToolName;
         console.log(`[TextToTool] ✅ Recognized tool name: ${tName}`);

         let args = toolData.arguments || toolData.args || toolData.parameters;
         if (!args) {
            // Extract ALL properties except 'tool' and 'name' as arguments
            args = { ...toolData };
            delete args.tool;
            delete args.name;
            console.log(`[TextToTool] 📦 Extracted arguments from remaining properties:`, args);
         }

         // Preserve 'skill' parameter if present
         if (toolData.skill && !args.skill) {
            args.skill = toolData.skill;
            console.log(`[TextToTool] 🎯 Added skill parameter: ${toolData.skill}`);
         }

         // Validate: reject 'write' calls that have no content (broken extraction)
         if (tName === 'write' && !args.content) {
           console.log(`[TextToTool] ⚠️ Rejecting 'write' call with no content arg — parser extracted garbage`);
         } else if (!toolCalls.find(tc => tc.name === tName)) {
            console.log(`[TextToTool] 🧩 Formalized generic JSON tool call: ${tName} with args:`, args);
            // unshift to maintain order since we process backwards
            toolCalls.unshift({
               id: `tc-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
               name: tName,
               arguments: args,
            });
            identifiedCall = true;
         }
      } else {
         console.log(`[TextToTool] 🔄 Tool not found in 'tool' or 'name' field, checking nested format`);
         // Handle {"write": {"path": "..."}} format
         for (const t of definedTools) {
           const toolName = t.name;
           if (toolData[toolName] && !toolCalls.find(tc => tc.name === toolName && JSON.stringify(tc.arguments) === JSON.stringify(toolData[toolName]))) {
             console.log(`[TextToTool] 🧩 Formalized JSON-narrated tool call: ${toolName}`);
             toolCalls.unshift({
               id: `tc-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
               name: toolName,
               arguments: toolData[toolName],
             });
             identifiedCall = true;
           }
         }
      }

      if (identifiedCall) {
        let removeStart = block.start;
        let removeEnd = block.end + 1;

        // Surgical cleanup: If the JSON was wrapped in a markdown fence, expand removal bounds to eat the fences
        const beforeBlock = scrubbedContent.slice(lastCopiedIndex, removeStart);
        const fenceBefore = beforeBlock.match(/```[a-zA-Z]*\s*\n?$/i);
        if (fenceBefore) {
           removeStart -= fenceBefore[0].length;
        }

        const afterBlock = scrubbedContent.slice(removeEnd);
        const fenceAfter = afterBlock.match(/^\n?\s*```/);
        if (fenceAfter) {
           removeEnd += fenceAfter[0].length;
        }

        // Append everything from last point to the start of what we're removing
        newScrubbedContent += scrubbedContent.slice(lastCopiedIndex, removeStart);
        lastCopiedIndex = removeEnd;
      }

    }

    // Add any remaining text
    newScrubbedContent += scrubbedContent.slice(lastCopiedIndex);
    scrubbedContent = newScrubbedContent.trim();

  } catch (e) {
    console.error(`[TextToTool] ❌ JSON parse error: ${e instanceof Error ? e.message : String(e)}`);
  }

  console.log(`[TextToTool] ✅ Parser complete: Found ${toolCalls.length} tool calls`);
  if (toolCalls.length > 0) {
    for (const tc of toolCalls) {
      console.log(`   • ${tc.name} with args: ${JSON.stringify(tc.arguments)}`);
    }

    // ── Validate and correct skill paths ────────────────────────────────
    console.log(`[TextToTool] ✓ Validating skill paths and arguments...`);
    for (const tc of toolCalls) {
      // Check for 'skill' parameter and validate/correct it
      if (tc.arguments.skill && typeof tc.arguments.skill === 'string') {
        const providedSkill = tc.arguments.skill;
        console.log(`[TextToTool]   🔍 Validating skill: ${providedSkill}`);

        const validation = validateAndCorrectSkillPath(providedSkill);
        if (!validation.isValid && validation.correctedPath) {
          console.log(`[TextToTool]   🔁 Auto-correcting skill path:`);
          console.log(`[TextToTool]      From: ${providedSkill}`);
          console.log(`[TextToTool]      To:   ${validation.correctedPath}`);
          console.log(`[TextToTool]      Confidence: ${(validation.confidence! * 100).toFixed(1)}%`);
          tc.arguments.skill = validation.correctedPath;
        } else if (validation.isValid) {
          console.log(`[TextToTool]   ✅ Skill path is valid: ${providedSkill}`);
        }
      }

      // Check for 'path' parameter that might be a skill path
      if (tc.arguments.path && typeof tc.arguments.path === 'string') {
        let providedPath = tc.arguments.path;

        // Sanitize path: remove leading invalid characters (colons, slashes, etc)
        const originalPath = providedPath;
        providedPath = providedPath.replace(/^[:\/\\]+/, '').trim();

        if (providedPath !== originalPath) {
          console.log(`[TextToTool]   🔧 Sanitized path: "${originalPath}" -> "${providedPath}"`);
          tc.arguments.path = providedPath; // Update to sanitized version
        }

        // Check if it looks like a skill path (contains .everfern/skills specifically)
        // Do NOT validate non-skill paths like .everfern/exec or .everfern/sites
        if (providedPath.includes('.everfern/skills') || providedPath.includes('.everfern\\skills')) {
          console.log(`[TextToTool]   🔍 Validating path: ${providedPath}`);
          const resolved = resolveSkillPath(providedPath);
          if (resolved) {
            console.log(`[TextToTool]   ✅ Path resolved: ${resolved}`);
            tc.arguments.path = resolved;
          }
        }
      }
    }
  }
  console.log(`[TextToTool] 📄 Scrubbed content length: ${scrubbedContent.length} chars`);

  // ── SMART TOOL EXECUTION STRATEGY ────────────────────────────────────────────
  // Use ReAct pattern (one tool per turn) for risky operations to prevent race conditions
  // Allow parallel execution for safe, independent tools for better performance
  if (toolCalls.length > 1) {
    const riskyTools = new Set(['run_command', 'bash', 'write', 'edit', 'delete', 'apply_patch', 'system_files']);
    const hasRiskyTool = toolCalls.some(tc => riskyTools.has(tc.name));
    
    if (hasRiskyTool) {
      console.log(`[TextToTool] 🔀 Limiting ${toolCalls.length} tool calls to first one only (ReAct pattern - risky operation detected)`);
      const firstCall = toolCalls[0];
      return { toolCalls: [firstCall], scrubbedContent, parseError: parseErrorStr };
    } else {
      console.log(`[TextToTool] ⚡ Allowing ${toolCalls.length} parallel tool calls (all safe operations)`);
    }
  }

  // Detect and remove duplicate tool calls (AI sometimes repeats itself)
  const uniqueToolCalls: ToolCall[] = [];
  const seenCalls = new Set<string>();

  for (const call of toolCalls) {
    // Create a deduplication key: name + serialized args
    const callKey = `${call.name}:${JSON.stringify(call.arguments)}`;
    
    if (seenCalls.has(callKey)) {
      console.log(`[TextToTool] 🔁 DUPLICATE DETECTED: Skipping duplicate call to ${call.name} with same args`);
      continue;
    }
    
    seenCalls.add(callKey);
    uniqueToolCalls.push(call);
  }

  if (uniqueToolCalls.length < toolCalls.length) {
    console.log(`[TextToTool] 🧹 Removed ${toolCalls.length - uniqueToolCalls.length} duplicate tool call(s)`);
  }

  return { toolCalls: uniqueToolCalls, scrubbedContent, parseError: parseErrorStr };
}
